version: "3"

services:
  api:
    build: .
    image: speakeasy:latest
    ports:
      - "8080:8080"
    env_file:
      - .env.prod

  database:
    image: mongo
    ports:
    - "27017"
    volumes:
     - data:/data/db

volumes:
  data:
